src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnswersRepository::class)]
class Answers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $answered_at = null;

    #[ORM\ManyToOne(inversedBy: 'answers')]
    private ?Comment $comment = null;

    #[ORM\ManyToOne(inversedBy: 'answers')]
    private ?User $user = null;

    public function __construct()
    {
        $this->answered_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getAnsweredAt(): ?\DateTimeImmutable
    {
        return $this->answered_at;
    }

    public function setAnsweredAt(\DateTimeImmutable $answered_at): static
    {
        $this->answered_at = $answered_at;

        return $this;
    }

    public function getComment(): ?Comment
    {
        return $this->comment;
    }

    public function setComment(?Comment $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $commented_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Publications $publication = null;

    /**
     * @var Collection<int, Answers>
     */
    #[ORM\OneToMany(targetEntity: Answers::class, mappedBy: 'comment')]
    private Collection $answers;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $User = null;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->commented_at = new \DateTimeImmutable();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getCommentedAt(): ?\DateTimeImmutable
    {
        return $this->commented_at;
    }

    public function setCommentedAt(\DateTimeImmutable $commented_at): static
    {
        $this->commented_at = $commented_at;

        return $this;
    }

    public function getPublication(): ?Publications
    {
        return $this->publication;
    }

    public function setPublication(?Publications $publication): static
    {
        $this->publication = $publication;

        return $this;
    }

    /**
     * @return Collection<int, Answers>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): static
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setComment($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): static
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getComment() === $this) {
                $answer->setComment(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Publications.php
<?php

namespace App\Entity;

use App\Repository\PublicationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PublicationsRepository::class)]
class Publications
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $published_at = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'publication')]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'publications')]
    private ?User $user = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->published_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeImmutable $published_at): static
    {
        $this->published_at = $published_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPublication($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPublication() === $this) {
                $comment->setPublication(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Answers;
use App\Entity\Comment;
use App\Entity\Publications;
use App\Form\AnswersType;
use App\Form\CommentType;
use App\Form\PublicationsType;
use App\Repository\PublicationsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/forum')]
class ForumController extends AbstractController
{
    #[Route('/', name: 'app_forum')]
    public function index(PublicationsRepository $publicationsRepository): Response
    {
        return $this->render('forum/publication.html.twig', [
            'publications' => $publicationsRepository->findAll(),
        ]);
    }

    #[Route('/publication/new', name: 'app_publications_new', methods: ['GET', 'POST'])]
    public function newPublication(Request $request, EntityManagerInterface $entityManager): Response
    {
        $publication = new Publications();
        $publication->setUser($this->getUser());
        $form = $this->createForm(PublicationsType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($publication);
            $entityManager->flush();

            return $this->redirectToRoute('app_forum', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('publications/new.html.twig', [
            'publication' => $publication,
            'form' => $form,
        ]);
    }

    #[Route('/publication/{id}/edit', name: 'app_publications_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Publications $publication, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PublicationsType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_forum', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('publications/edit.html.twig', [
            'publication' => $publication,
            'form' => $form,
        ]);
    }

    #[Route('/publication/{id}', name: 'app_publications_delete', methods: ['POST'])]
    public function delete(Request $request, Publications $publication, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $publication->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($publication);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_forum', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/publications/{id}', name: 'app_forum_show', methods: ['GET'])]
    public function showPublications(Publications $publications): Response
    {
        return $this->render('forum/comment.html.twig', [
            'publication' => $publications,
            'comments' => $publications->getComments(),
        ]);
    }

    #[Route('/comment/new/{publicationId}', name: 'app_comment_new', methods: ['GET', 'POST'])]
    public function newComment(Request $request, int $publicationId, EntityManagerInterface $entityManager): Response
    {
        $publication = $entityManager->getRepository(Publications::class)->find($publicationId);

        if (!$publication) {
            throw $this->createNotFoundException('La publication correspondante n\'a pas été trouvée.');
        }
        $comment = new Comment();
        $comment->setPublication($publication);
        $comment->setUser($this->getUser());

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('app_forum_show', ['id' => $publication->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/comment/{publicationId}/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function editComment(Request $request, int $publicationId, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        $publication = $entityManager->getRepository(Publications::class)->find($publicationId);

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_forum_show', ['id' => $publication->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/comment/{id}', name: 'app_comment_delete', methods: ['POST'])]
    public function deleteComment(Request $request, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        // Vérifiez si le jeton CSRF est valide
        if ($this->isCsrfTokenValid('delete' . $comment->getId(), $request->request->get('_token'))) {
            // Supprimez le commentaire
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        // Redirigez vers la page où les commentaires sont affichés
        return $this->redirectToRoute('app_forum_show', ['id' => $comment->getPublication()->getId()], Response::HTTP_SEE_OTHER);
    }


    #[Route('/comment/{id}', name: 'app_comment_show', methods: ['GET'])]
    public function showComment(Comment $comment): Response
    {
        return $this->render('forum/answer.html.twig', [
            'comment' => $comment,
            'answers' => $comment->getAnswers(),
        ]);
    }

    #[Route('/new/{commentId}', name: 'app_answers_new', methods: ['GET', 'POST'])]
    public function newAnswer(Request $request, int $commentId, EntityManagerInterface $entityManager): Response
    {
        $comment = $entityManager->getRepository(Comment::class)->find($commentId);

        if (!$comment) {
            throw $this->createNotFoundException('Le commentaire correspondante n\'a pas été trouvée.');
        }
        $answer = new Answers();
        $answer->setComment($comment);
        $answer->setUser($this->getUser());

        $form = $this->createForm(AnswersType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('app_comment_show', ['id' => $comment->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answers/new.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'comment' => $comment
        ]);
    }

    #[Route('/{commentId}/{id}/edit', name: 'app_answers_edit', methods: ['GET', 'POST'])]
    public function editAnswer(Request $request, int $commentId, Answers $answer, EntityManagerInterface $entityManager): Response
    {
        $comment = $entityManager->getRepository(Comment::class)->find($commentId);

        $form = $this->createForm(AnswersType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_comment_show', ['id' => $comment->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answers/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
            'comment' => $comment
        ]);
    }

    #[Route('/{commentId}/{id}', name: 'app_answers_delete', methods: ['POST'])]
    public function deleteAnswer(Request $request, int $commentId, Answers $answer, EntityManagerInterface $entityManager): Response
    {
        $comment = $entityManager->getRepository(Comment::class)->find($commentId);

        if ($this->isCsrfTokenValid('delete' . $answer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($answer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_comment_show', ['id' => $comment->getId()], Response::HTTP_SEE_OTHER);
    }
}

templates/forum/answer.html.twig
{% extends 'base.html.twig' %}

		{% block title %}
			Publications
		{% endblock %}

		{% block body %}
			<div class="py-8 mx-auto max-w-7xl">
				<h1 class="mb-4 text-3xl font-bold">
					{{ comment.body }}
				</h1>

				<h2 class="mb-4 font-semibold underline">
					Comments
				</h2>
				{% if answers %}
					<div class="overflow-x-auto">
						<table class="min-w-full bg-white border border-gray-200">
							<thead>
								<tr>
									<th class="px-4 py-2 border-b">
										ID
									</th>
									<th class="px-4 py-2 border-b">
										Comment
									</th>
									<th class="px-4 py-2 border-b">
										Posted At
									</th>
									<th class="px-4 py-2 border-b">
										User
									</th>
									<th class="px-4 py-2 border-b">
										Actions
									</th>
								</tr>
							</thead>
							<tbody>
								{% for answer in answers %}
									<tr class="hover:bg-gray-100">
										<td class="px-4 py-2 border-b">
											{{ answer.id }}
										</td>
										<td class="px-4 py-2 border-b">
											{{ answer.body }}
										</td>
										<td class="px-4 py-2 border-b">
											{{ answer.answeredAt|date('d-m-Y H:i') }}
										</td>
										<td class="px-4 py-2 border-b">
											{{ answer.user.pseudo }}
										</td>
										<td class="px-4 py-2 border-b">
											<a href="{{ path('app_answers_edit', {'commentId': comment.id,'id': answer.id}) }}" class="px-2 py-1 text-white bg-blue-500 rounded hover:bg-blue-700">
												Edit
											</a>
											{{ include('answers/_delete_form.html.twig') }}
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<p class="text-gray-500">
						No comments found.
					</p>
				{% endif %}

				<div class="mt-6">
					<a href="{{ path('app_answers_new', {'commentId': comment.id}) }}" class="inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-lg shadow-md hover:bg-blue-700">
						Add a Comment
					</a>
				</div>
				<div class="mt-6">
					{{ include('comment/_delete_form.html.twig') }}
				</div>

			</div>
		{% endblock %}

templates/forum/comment.html.twig
{% extends 'base.html.twig' %}

		{% block title %}
			Publications
		{% endblock %}

		{% block body %}
			<div class="py-8 mx-auto max-w-7xl">
				<h1 class="mb-4 text-3xl font-bold">
					{{ publication.body }}
				</h1>

				<h2 class="mb-4 font-semibold underline">
					Comments
				</h2>
{% if comments %}
			<div class="overflow-x-auto">
				<table class="min-w-full bg-white border border-gray-200">
					<thead>
						<tr>
							<th class="px-4 py-2 border-b">
								ID
							</th>
							<th class="px-4 py-2 border-b">
								Comment
							</th>
							<th class="px-4 py-2 border-b">
								Posted At
							</th>
							<th class="px-4 py-2 border-b">
								User
							</th>
							<th class="px-4 py-2 border-b">
								Actions
							</th>
						</tr>
					</thead>
					<tbody>
						{% for comment in comments %}
							<tr class="hover:bg-gray-100">
								<td class="px-4 py-2 border-b">
									{{ comment.id }}
								</td>
								<td class="px-4 py-2 border-b">
									{{ comment.body }}
								</td>
								<td class="px-4 py-2 border-b">
									{{ comment.commentedAt|date('d-m-Y H:i') }}
								</td>
								<td class="px-4 py-2 border-b">
									{{ comment.user.pseudo }}
								</td>
								<td class="px-4 py-2 border-b">
									<a href="{{ path('app_comment_show', {'id': comment.id}) }}" class="px-2 py-1 text-white bg-green-500 rounded hover:bg-green-700">
										Show
									</a>
									<a href="{{ path('app_comment_edit', {'publicationId': publication.id,'id': comment.id}) }}" class="px-2 py-1 text-white bg-blue-500 rounded hover:bg-blue-700">
										Edit
									</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		{% else %}
			<p class="text-gray-500">
				No comments found.
			</p>
		{% endif %}

		<div class="mt-6">
			<a href="{{ path('app_comment_new', {'publicationId': publication.id}) }}" class="inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-lg shadow-md hover:bg-blue-700">
				Add a Comment
			</a>
		</div>

		<div class="mt-6">
			{{ include('publications/_delete_form.html.twig') }}
		</div>
	</div>
{% endblock %}

templates/forum/publication.html.twig
{% extends 'base.html.twig' %}

		{% block title %}
			The Forum
		{% endblock %}

		{% block body %}
			<h1 class="mb-4 text-2xl font-bold">
				The Forum
			</h1>

			<table class="min-w-full divide-y divide-gray-200">
				<thead>
					<tr>
						<th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
							Id
						</th>
						<th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
							Body
						</th>
						<th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
							Img
						</th>
						<th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
							Published At
						</th>
						<th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
							Actions
						</th>
					</tr>
				</thead>
				<tbody class="bg-white divide-y divide-gray-200">
					{% for publication in publications %}
						<tr>
							<td class="px-6 py-4 whitespace-nowrap">
								{{ publication.id }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap">
								{{ publication.body }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap">
								{{ publication.img }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap">
								{{ publication.publishedAt ? publication.publishedAt|date('Y-m-d H:i:s') : '' }}
							</td>
							<td class="px-6 py-4 text-sm font-medium whitespace-nowrap">
								<a href="{{ path('app_forum_show', {'id': publication.id}) }}" class="text-indigo-600 hover:text-indigo-900">
									Show
								</a>
								<a href="{{ path('app_publications_edit', {'id': publication.id}) }}" class="ml-2 text-indigo-600 hover:text-indigo-900">
									Edit
								</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="5" class="px-6 py-4 whitespace-nowrap">
								No records found
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

			<a href="{{ path('app_publications_new') }}" class="inline-block px-4 py-2 mt-4 font-semibold text-white bg-indigo-500 rounded-md hover:bg-indigo-600">
				Create New
			</a>
		{% endblock %}